version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - 8081:80
      - 8082:443
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./:/var/www

  php-fpm:
    image: php:fpm
    volumes:
      - ./:/var/www
